<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all"/>
    </ItemGroup>

    <Target Name="PnpmInstall" BeforeTargets="TailwindCssGenerate" Inputs="package.json" Outputs="node_modules/.pnpm/lock.yaml">
        <Exec Command="pnpm install"/>
    </Target>

    <ItemGroup>
        <TailwindContent Include="wwwroot/css/tailwind.in.css" />
        <TailwindContent Include="$(ProjectDir)**/*.razor"/>
        <TailwindContent Include="$(ProjectDir)**/*.razor.css"/>
        
        <Content Remove="wwwroot/css/tailwind.in.css" />
    </ItemGroup>

    <Target Name="TailwindCssGenerate" BeforeTargets="PreBuildEvent" Inputs="@(TailwindContent)" Outputs="wwwroot/css/tailwind.css">
        <Exec Command="pnpx @tailwindcss/cli --minify --input $(ProjectDir)wwwroot/css/tailwind.in.css --output $(ProjectDir)wwwroot/css/tailwind.css"/>
    </Target>
    
    <ItemGroup>
        <TailwindArtifacts Include="wwwroot/css/tailwind.css" />
    </ItemGroup>
    
    <Target Name="TailwindCssClean" AfterTargets="Clean">
        <Delete Files="@(TailwindArtifacts)" />
    </Target>
    
    <Target Name="NodeModulesClean" AfterTargets="Clean">
        <RemoveDir Directories="node_modules" />
    </Target>

</Project>
